### PR TITLE
#11 Barcode error messages modified

### PR DESCRIPTION
**Pull request by Bahaaib**
Track issue here: 
https://github.com/ammaratef45/Attendance/issues/11

### CODE REVIEW

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#16](https://github.com/ammaratef45/attendance/issues/16) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#16](https://github.com/ammaratef45/attendance/issues/16); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by ammaratef45** [comment]
@Bahaaib Thanks 👍

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#16` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#16](https://github.com/ammaratef45/attendance/issues/16) is now out of scope

**Pull request merged**
