### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Nermeen78**

### CODE REVIEW

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this pull request

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#33](https://github.com/ammaratef45/attendance/issues/33) is now in scope, role is `REV`

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `REV` is banned at [#33](https://github.com/ammaratef45/attendance/issues/33); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#33` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#33](https://github.com/ammaratef45/attendance/issues/33) is now out of scope

**Pull request merged**
