### PR TITLE
Performance tools section Added to README.md

### PR DESCRIPTION
**Pull request by Bahaaib**
track issue here:
https://github.com/ammaratef45/Attendance/issues/22

### CODE REVIEW

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this pull request

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#34](https://github.com/ammaratef45/attendance/issues/34) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#34` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#34](https://github.com/ammaratef45/attendance/issues/34) is now out of scope

**Pull request merged**
