### PR TITLE
Cleaned Profile Module from Dart warnings

### PR DESCRIPTION
**Pull request by Bahaaib**
Follow issue here : 
#52

### CODE REVIEW

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this pull request

**Comment by ammaratef45** [comment]
@Bahaaib thanks, the ci is broken because of problem with python in the docker image so I will merge this manually till we solve it.
Please check if you can help with it.

**Comment by Bahaaib** [comment]
Okay. thanks!

**Comment by 0crat** [comment]
Job [#53](https://github.com/ammaratef45/attendance/issues/53) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#53` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#53](https://github.com/ammaratef45/attendance/issues/53) is now out of scope

**Pull request merged**
